import sys

sys.path.append("../cleanrl")

MW_DATA_DIR = "/PATH/TO/METAWORLD_DATA_DIR/"
CAPTION_PATH = MW_DATA_DIR
CHKPT_PATH = "/PATH/TO/C4C_CHECKPOINT_DIR/"
DATA_PATH = MW_DATA_DIR
EXP_DIR = "/PATH/TO/EXP_OUTPUT_DIR/"
